<?php
/**
 * ApplicationsApi
 * PHP version 7.2
 *
 * @category Class
 * @package  MergeATSClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Merge ATS API
 *
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MergeATSClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use MergeATSClient\ApiException;
use MergeATSClient\Configuration;
use MergeATSClient\HeaderSelector;
use MergeATSClient\ObjectSerializer;

/**
 * ApplicationsApi Class Doc Comment
 *
 * @category Class
 * @package  MergeATSClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ApplicationsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation applicationsChangeStageCreate
     *
     * @param  string $x_account_token Token identifying the end user. (required)
     * @param  string $id id (required)
     * @param  bool $is_debug_mode Whether to include debug fields (such as log file links) in the response. (optional)
     * @param  bool $run_async Whether or not third-party updates should be run asynchronously. (optional)
     * @param  \MergeATSClient\Model\UpdateApplicationStageRequest $update_application_stage_request update_application_stage_request (optional)
     *
     * @throws \MergeATSClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \MergeATSClient\Model\ApplicationResponse
     */
    public function applicationsChangeStageCreate($x_account_token, $id, $is_debug_mode = null, $run_async = null, $update_application_stage_request = null)
    {
        list($response) = $this->applicationsChangeStageCreateWithHttpInfo($x_account_token, $id, $is_debug_mode, $run_async, $update_application_stage_request);
        return $response;
    }

    /**
     * Operation applicationsChangeStageCreateWithHttpInfo
     *
     * @param  string $x_account_token Token identifying the end user. (required)
     * @param  string $id (required)
     * @param  bool $is_debug_mode Whether to include debug fields (such as log file links) in the response. (optional)
     * @param  bool $run_async Whether or not third-party updates should be run asynchronously. (optional)
     * @param  \MergeATSClient\Model\UpdateApplicationStageRequest $update_application_stage_request (optional)
     *
     * @throws \MergeATSClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \MergeATSClient\Model\ApplicationResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function applicationsChangeStageCreateWithHttpInfo($x_account_token, $id, $is_debug_mode = null, $run_async = null, $update_application_stage_request = null)
    {
        $request = $this->applicationsChangeStageCreateRequest($x_account_token, $id, $is_debug_mode, $run_async, $update_application_stage_request);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 201:
                    if ('\MergeATSClient\Model\ApplicationResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MergeATSClient\Model\ApplicationResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\MergeATSClient\Model\ApplicationResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MergeATSClient\Model\ApplicationResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation applicationsChangeStageCreateAsync
     *
     * @param  string $x_account_token Token identifying the end user. (required)
     * @param  string $id (required)
     * @param  bool $is_debug_mode Whether to include debug fields (such as log file links) in the response. (optional)
     * @param  bool $run_async Whether or not third-party updates should be run asynchronously. (optional)
     * @param  \MergeATSClient\Model\UpdateApplicationStageRequest $update_application_stage_request (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function applicationsChangeStageCreateAsync($x_account_token, $id, $is_debug_mode = null, $run_async = null, $update_application_stage_request = null)
    {
        return $this->applicationsChangeStageCreateAsyncWithHttpInfo($x_account_token, $id, $is_debug_mode, $run_async, $update_application_stage_request)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation applicationsChangeStageCreateAsyncWithHttpInfo
     *
     * @param  string $x_account_token Token identifying the end user. (required)
     * @param  string $id (required)
     * @param  bool $is_debug_mode Whether to include debug fields (such as log file links) in the response. (optional)
     * @param  bool $run_async Whether or not third-party updates should be run asynchronously. (optional)
     * @param  \MergeATSClient\Model\UpdateApplicationStageRequest $update_application_stage_request (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function applicationsChangeStageCreateAsyncWithHttpInfo($x_account_token, $id, $is_debug_mode = null, $run_async = null, $update_application_stage_request = null)
    {
        $returnType = '\MergeATSClient\Model\ApplicationResponse';
        $request = $this->applicationsChangeStageCreateRequest($x_account_token, $id, $is_debug_mode, $run_async, $update_application_stage_request);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'applicationsChangeStageCreate'
     *
     * @param  string $x_account_token Token identifying the end user. (required)
     * @param  string $id (required)
     * @param  bool $is_debug_mode Whether to include debug fields (such as log file links) in the response. (optional)
     * @param  bool $run_async Whether or not third-party updates should be run asynchronously. (optional)
     * @param  \MergeATSClient\Model\UpdateApplicationStageRequest $update_application_stage_request (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function applicationsChangeStageCreateRequest($x_account_token, $id, $is_debug_mode = null, $run_async = null, $update_application_stage_request = null)
    {
        // verify the required parameter 'x_account_token' is set
        if ($x_account_token === null || (is_array($x_account_token) && count($x_account_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_account_token when calling applicationsChangeStageCreate'
            );
        }
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling applicationsChangeStageCreate'
            );
        }

        $resourcePath = '/applications/{id}/change-stage';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($is_debug_mode !== null) {
            if('form' === 'form' && is_array($is_debug_mode)) {
                foreach($is_debug_mode as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['is_debug_mode'] = $is_debug_mode;
            }
        }
        // query params
        if ($run_async !== null) {
            if('form' === 'form' && is_array($run_async)) {
                foreach($run_async as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['run_async'] = $run_async;
            }
        }

        // header params
        if ($x_account_token !== null) {
            $headerParams['X-Account-Token'] = ObjectSerializer::toHeaderValue($x_account_token);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data']
            );
        }

        // for model (json/xml)
        if (isset($update_application_stage_request)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($update_application_stage_request));
            } else {
                $httpBody = $update_application_stage_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation applicationsCreate
     *
     * @param  string $x_account_token Token identifying the end user. (required)
     * @param  \MergeATSClient\Model\ApplicationEndpointRequest $application_endpoint_request application_endpoint_request (required)
     * @param  bool $is_debug_mode Whether to include debug fields (such as log file links) in the response. (optional)
     * @param  bool $run_async Whether or not third-party updates should be run asynchronously. (optional)
     *
     * @throws \MergeATSClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \MergeATSClient\Model\ApplicationResponse
     */
    public function applicationsCreate($x_account_token, $application_endpoint_request, $is_debug_mode = null, $run_async = null)
    {
        list($response) = $this->applicationsCreateWithHttpInfo($x_account_token, $application_endpoint_request, $is_debug_mode, $run_async);
        return $response;
    }

    /**
     * Operation applicationsCreateWithHttpInfo
     *
     * @param  string $x_account_token Token identifying the end user. (required)
     * @param  \MergeATSClient\Model\ApplicationEndpointRequest $application_endpoint_request (required)
     * @param  bool $is_debug_mode Whether to include debug fields (such as log file links) in the response. (optional)
     * @param  bool $run_async Whether or not third-party updates should be run asynchronously. (optional)
     *
     * @throws \MergeATSClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \MergeATSClient\Model\ApplicationResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function applicationsCreateWithHttpInfo($x_account_token, $application_endpoint_request, $is_debug_mode = null, $run_async = null)
    {
        $request = $this->applicationsCreateRequest($x_account_token, $application_endpoint_request, $is_debug_mode, $run_async);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 201:
                    if ('\MergeATSClient\Model\ApplicationResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MergeATSClient\Model\ApplicationResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\MergeATSClient\Model\ApplicationResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MergeATSClient\Model\ApplicationResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation applicationsCreateAsync
     *
     * @param  string $x_account_token Token identifying the end user. (required)
     * @param  \MergeATSClient\Model\ApplicationEndpointRequest $application_endpoint_request (required)
     * @param  bool $is_debug_mode Whether to include debug fields (such as log file links) in the response. (optional)
     * @param  bool $run_async Whether or not third-party updates should be run asynchronously. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function applicationsCreateAsync($x_account_token, $application_endpoint_request, $is_debug_mode = null, $run_async = null)
    {
        return $this->applicationsCreateAsyncWithHttpInfo($x_account_token, $application_endpoint_request, $is_debug_mode, $run_async)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation applicationsCreateAsyncWithHttpInfo
     *
     * @param  string $x_account_token Token identifying the end user. (required)
     * @param  \MergeATSClient\Model\ApplicationEndpointRequest $application_endpoint_request (required)
     * @param  bool $is_debug_mode Whether to include debug fields (such as log file links) in the response. (optional)
     * @param  bool $run_async Whether or not third-party updates should be run asynchronously. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function applicationsCreateAsyncWithHttpInfo($x_account_token, $application_endpoint_request, $is_debug_mode = null, $run_async = null)
    {
        $returnType = '\MergeATSClient\Model\ApplicationResponse';
        $request = $this->applicationsCreateRequest($x_account_token, $application_endpoint_request, $is_debug_mode, $run_async);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'applicationsCreate'
     *
     * @param  string $x_account_token Token identifying the end user. (required)
     * @param  \MergeATSClient\Model\ApplicationEndpointRequest $application_endpoint_request (required)
     * @param  bool $is_debug_mode Whether to include debug fields (such as log file links) in the response. (optional)
     * @param  bool $run_async Whether or not third-party updates should be run asynchronously. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function applicationsCreateRequest($x_account_token, $application_endpoint_request, $is_debug_mode = null, $run_async = null)
    {
        // verify the required parameter 'x_account_token' is set
        if ($x_account_token === null || (is_array($x_account_token) && count($x_account_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_account_token when calling applicationsCreate'
            );
        }
        // verify the required parameter 'application_endpoint_request' is set
        if ($application_endpoint_request === null || (is_array($application_endpoint_request) && count($application_endpoint_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $application_endpoint_request when calling applicationsCreate'
            );
        }

        $resourcePath = '/applications';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($is_debug_mode !== null) {
            if('form' === 'form' && is_array($is_debug_mode)) {
                foreach($is_debug_mode as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['is_debug_mode'] = $is_debug_mode;
            }
        }
        // query params
        if ($run_async !== null) {
            if('form' === 'form' && is_array($run_async)) {
                foreach($run_async as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['run_async'] = $run_async;
            }
        }

        // header params
        if ($x_account_token !== null) {
            $headerParams['X-Account-Token'] = ObjectSerializer::toHeaderValue($x_account_token);
        }



        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data']
            );
        }

        // for model (json/xml)
        if (isset($application_endpoint_request)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($application_endpoint_request));
            } else {
                $httpBody = $application_endpoint_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation applicationsList
     *
     * @param  string $x_account_token Token identifying the end user. (required)
     * @param  string $candidate_id If provided, will only return applications for this candidate. (optional)
     * @param  \DateTime $created_after If provided, will only return objects created after this datetime. (optional)
     * @param  \DateTime $created_before If provided, will only return objects created before this datetime. (optional)
     * @param  string $credited_to_id If provided, will only return applications credited to this user. (optional)
     * @param  string $current_stage_id If provided, will only return applications at this interview stage. (optional)
     * @param  string $cursor The pagination cursor value. (optional)
     * @param  bool $include_deleted_data Whether to include data that was marked as deleted by third party webhooks. (optional)
     * @param  bool $include_remote_data Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  string $job_id If provided, will only return applications for this job. (optional)
     * @param  \DateTime $modified_after If provided, will only return objects modified after this datetime. (optional)
     * @param  \DateTime $modified_before If provided, will only return objects modified before this datetime. (optional)
     * @param  int $page_size Number of results to return per page. (optional)
     * @param  string $reject_reason_id If provided, will only return applications with this reject reason. (optional)
     * @param  string $remote_id The API provider&#39;s ID for the given object. (optional)
     * @param  string $source If provided, will only return applications with this source. (optional)
     *
     * @throws \MergeATSClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \MergeATSClient\Model\PaginatedApplicationList
     */
    public function applicationsList($x_account_token, $candidate_id = null, $created_after = null, $created_before = null, $credited_to_id = null, $current_stage_id = null, $cursor = null, $include_deleted_data = null, $include_remote_data = null, $job_id = null, $modified_after = null, $modified_before = null, $page_size = null, $reject_reason_id = null, $remote_id = null, $source = null)
    {
        list($response) = $this->applicationsListWithHttpInfo($x_account_token, $candidate_id, $created_after, $created_before, $credited_to_id, $current_stage_id, $cursor, $include_deleted_data, $include_remote_data, $job_id, $modified_after, $modified_before, $page_size, $reject_reason_id, $remote_id, $source);
        return $response;
    }

    /**
     * Operation applicationsListWithHttpInfo
     *
     * @param  string $x_account_token Token identifying the end user. (required)
     * @param  string $candidate_id If provided, will only return applications for this candidate. (optional)
     * @param  \DateTime $created_after If provided, will only return objects created after this datetime. (optional)
     * @param  \DateTime $created_before If provided, will only return objects created before this datetime. (optional)
     * @param  string $credited_to_id If provided, will only return applications credited to this user. (optional)
     * @param  string $current_stage_id If provided, will only return applications at this interview stage. (optional)
     * @param  string $cursor The pagination cursor value. (optional)
     * @param  bool $include_deleted_data Whether to include data that was marked as deleted by third party webhooks. (optional)
     * @param  bool $include_remote_data Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  string $job_id If provided, will only return applications for this job. (optional)
     * @param  \DateTime $modified_after If provided, will only return objects modified after this datetime. (optional)
     * @param  \DateTime $modified_before If provided, will only return objects modified before this datetime. (optional)
     * @param  int $page_size Number of results to return per page. (optional)
     * @param  string $reject_reason_id If provided, will only return applications with this reject reason. (optional)
     * @param  string $remote_id The API provider&#39;s ID for the given object. (optional)
     * @param  string $source If provided, will only return applications with this source. (optional)
     *
     * @throws \MergeATSClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \MergeATSClient\Model\PaginatedApplicationList, HTTP status code, HTTP response headers (array of strings)
     */
    public function applicationsListWithHttpInfo($x_account_token, $candidate_id = null, $created_after = null, $created_before = null, $credited_to_id = null, $current_stage_id = null, $cursor = null, $include_deleted_data = null, $include_remote_data = null, $job_id = null, $modified_after = null, $modified_before = null, $page_size = null, $reject_reason_id = null, $remote_id = null, $source = null)
    {
        $request = $this->applicationsListRequest($x_account_token, $candidate_id, $created_after, $created_before, $credited_to_id, $current_stage_id, $cursor, $include_deleted_data, $include_remote_data, $job_id, $modified_after, $modified_before, $page_size, $reject_reason_id, $remote_id, $source);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\MergeATSClient\Model\PaginatedApplicationList' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MergeATSClient\Model\PaginatedApplicationList', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\MergeATSClient\Model\PaginatedApplicationList';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MergeATSClient\Model\PaginatedApplicationList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation applicationsListAsync
     *
     * @param  string $x_account_token Token identifying the end user. (required)
     * @param  string $candidate_id If provided, will only return applications for this candidate. (optional)
     * @param  \DateTime $created_after If provided, will only return objects created after this datetime. (optional)
     * @param  \DateTime $created_before If provided, will only return objects created before this datetime. (optional)
     * @param  string $credited_to_id If provided, will only return applications credited to this user. (optional)
     * @param  string $current_stage_id If provided, will only return applications at this interview stage. (optional)
     * @param  string $cursor The pagination cursor value. (optional)
     * @param  bool $include_deleted_data Whether to include data that was marked as deleted by third party webhooks. (optional)
     * @param  bool $include_remote_data Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  string $job_id If provided, will only return applications for this job. (optional)
     * @param  \DateTime $modified_after If provided, will only return objects modified after this datetime. (optional)
     * @param  \DateTime $modified_before If provided, will only return objects modified before this datetime. (optional)
     * @param  int $page_size Number of results to return per page. (optional)
     * @param  string $reject_reason_id If provided, will only return applications with this reject reason. (optional)
     * @param  string $remote_id The API provider&#39;s ID for the given object. (optional)
     * @param  string $source If provided, will only return applications with this source. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function applicationsListAsync($x_account_token, $candidate_id = null, $created_after = null, $created_before = null, $credited_to_id = null, $current_stage_id = null, $cursor = null, $include_deleted_data = null, $include_remote_data = null, $job_id = null, $modified_after = null, $modified_before = null, $page_size = null, $reject_reason_id = null, $remote_id = null, $source = null)
    {
        return $this->applicationsListAsyncWithHttpInfo($x_account_token, $candidate_id, $created_after, $created_before, $credited_to_id, $current_stage_id, $cursor, $include_deleted_data, $include_remote_data, $job_id, $modified_after, $modified_before, $page_size, $reject_reason_id, $remote_id, $source)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation applicationsListAsyncWithHttpInfo
     *
     * @param  string $x_account_token Token identifying the end user. (required)
     * @param  string $candidate_id If provided, will only return applications for this candidate. (optional)
     * @param  \DateTime $created_after If provided, will only return objects created after this datetime. (optional)
     * @param  \DateTime $created_before If provided, will only return objects created before this datetime. (optional)
     * @param  string $credited_to_id If provided, will only return applications credited to this user. (optional)
     * @param  string $current_stage_id If provided, will only return applications at this interview stage. (optional)
     * @param  string $cursor The pagination cursor value. (optional)
     * @param  bool $include_deleted_data Whether to include data that was marked as deleted by third party webhooks. (optional)
     * @param  bool $include_remote_data Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  string $job_id If provided, will only return applications for this job. (optional)
     * @param  \DateTime $modified_after If provided, will only return objects modified after this datetime. (optional)
     * @param  \DateTime $modified_before If provided, will only return objects modified before this datetime. (optional)
     * @param  int $page_size Number of results to return per page. (optional)
     * @param  string $reject_reason_id If provided, will only return applications with this reject reason. (optional)
     * @param  string $remote_id The API provider&#39;s ID for the given object. (optional)
     * @param  string $source If provided, will only return applications with this source. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function applicationsListAsyncWithHttpInfo($x_account_token, $candidate_id = null, $created_after = null, $created_before = null, $credited_to_id = null, $current_stage_id = null, $cursor = null, $include_deleted_data = null, $include_remote_data = null, $job_id = null, $modified_after = null, $modified_before = null, $page_size = null, $reject_reason_id = null, $remote_id = null, $source = null)
    {
        $returnType = '\MergeATSClient\Model\PaginatedApplicationList';
        $request = $this->applicationsListRequest($x_account_token, $candidate_id, $created_after, $created_before, $credited_to_id, $current_stage_id, $cursor, $include_deleted_data, $include_remote_data, $job_id, $modified_after, $modified_before, $page_size, $reject_reason_id, $remote_id, $source);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'applicationsList'
     *
     * @param  string $x_account_token Token identifying the end user. (required)
     * @param  string $candidate_id If provided, will only return applications for this candidate. (optional)
     * @param  \DateTime $created_after If provided, will only return objects created after this datetime. (optional)
     * @param  \DateTime $created_before If provided, will only return objects created before this datetime. (optional)
     * @param  string $credited_to_id If provided, will only return applications credited to this user. (optional)
     * @param  string $current_stage_id If provided, will only return applications at this interview stage. (optional)
     * @param  string $cursor The pagination cursor value. (optional)
     * @param  bool $include_deleted_data Whether to include data that was marked as deleted by third party webhooks. (optional)
     * @param  bool $include_remote_data Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     * @param  string $job_id If provided, will only return applications for this job. (optional)
     * @param  \DateTime $modified_after If provided, will only return objects modified after this datetime. (optional)
     * @param  \DateTime $modified_before If provided, will only return objects modified before this datetime. (optional)
     * @param  int $page_size Number of results to return per page. (optional)
     * @param  string $reject_reason_id If provided, will only return applications with this reject reason. (optional)
     * @param  string $remote_id The API provider&#39;s ID for the given object. (optional)
     * @param  string $source If provided, will only return applications with this source. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function applicationsListRequest($x_account_token, $candidate_id = null, $created_after = null, $created_before = null, $credited_to_id = null, $current_stage_id = null, $cursor = null, $include_deleted_data = null, $include_remote_data = null, $job_id = null, $modified_after = null, $modified_before = null, $page_size = null, $reject_reason_id = null, $remote_id = null, $source = null)
    {
        // verify the required parameter 'x_account_token' is set
        if ($x_account_token === null || (is_array($x_account_token) && count($x_account_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_account_token when calling applicationsList'
            );
        }

        $resourcePath = '/applications';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($candidate_id !== null) {
            if('form' === 'form' && is_array($candidate_id)) {
                foreach($candidate_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['candidate_id'] = $candidate_id;
            }
        }
        // query params
        if ($created_after !== null) {
            if('form' === 'form' && is_array($created_after)) {
                foreach($created_after as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['created_after'] = $created_after;
            }
        }
        // query params
        if ($created_before !== null) {
            if('form' === 'form' && is_array($created_before)) {
                foreach($created_before as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['created_before'] = $created_before;
            }
        }
        // query params
        if ($credited_to_id !== null) {
            if('form' === 'form' && is_array($credited_to_id)) {
                foreach($credited_to_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['credited_to_id'] = $credited_to_id;
            }
        }
        // query params
        if ($current_stage_id !== null) {
            if('form' === 'form' && is_array($current_stage_id)) {
                foreach($current_stage_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['current_stage_id'] = $current_stage_id;
            }
        }
        // query params
        if ($cursor !== null) {
            if('form' === 'form' && is_array($cursor)) {
                foreach($cursor as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['cursor'] = $cursor;
            }
        }
        // query params
        if ($include_deleted_data !== null) {
            if('form' === 'form' && is_array($include_deleted_data)) {
                foreach($include_deleted_data as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['include_deleted_data'] = $include_deleted_data;
            }
        }
        // query params
        if ($include_remote_data !== null) {
            if('form' === 'form' && is_array($include_remote_data)) {
                foreach($include_remote_data as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['include_remote_data'] = $include_remote_data;
            }
        }
        // query params
        if ($job_id !== null) {
            if('form' === 'form' && is_array($job_id)) {
                foreach($job_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['job_id'] = $job_id;
            }
        }
        // query params
        if ($modified_after !== null) {
            if('form' === 'form' && is_array($modified_after)) {
                foreach($modified_after as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['modified_after'] = $modified_after;
            }
        }
        // query params
        if ($modified_before !== null) {
            if('form' === 'form' && is_array($modified_before)) {
                foreach($modified_before as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['modified_before'] = $modified_before;
            }
        }
        // query params
        if ($page_size !== null) {
            if('form' === 'form' && is_array($page_size)) {
                foreach($page_size as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['page_size'] = $page_size;
            }
        }
        // query params
        if ($reject_reason_id !== null) {
            if('form' === 'form' && is_array($reject_reason_id)) {
                foreach($reject_reason_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['reject_reason_id'] = $reject_reason_id;
            }
        }
        // query params
        if ($remote_id !== null) {
            if('form' === 'form' && is_array($remote_id)) {
                foreach($remote_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['remote_id'] = $remote_id;
            }
        }
        // query params
        if ($source !== null) {
            if('form' === 'form' && is_array($source)) {
                foreach($source as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['source'] = $source;
            }
        }

        // header params
        if ($x_account_token !== null) {
            $headerParams['X-Account-Token'] = ObjectSerializer::toHeaderValue($x_account_token);
        }



        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation applicationsMetaPostRetrieve
     *
     * @param  string $x_account_token Token identifying the end user. (required)
     * @param  string $application_remote_template_id The template ID associated with the nested application in the request. (optional)
     *
     * @throws \MergeATSClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \MergeATSClient\Model\MetaResponse
     */
    public function applicationsMetaPostRetrieve($x_account_token, $application_remote_template_id = null)
    {
        list($response) = $this->applicationsMetaPostRetrieveWithHttpInfo($x_account_token, $application_remote_template_id);
        return $response;
    }

    /**
     * Operation applicationsMetaPostRetrieveWithHttpInfo
     *
     * @param  string $x_account_token Token identifying the end user. (required)
     * @param  string $application_remote_template_id The template ID associated with the nested application in the request. (optional)
     *
     * @throws \MergeATSClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \MergeATSClient\Model\MetaResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function applicationsMetaPostRetrieveWithHttpInfo($x_account_token, $application_remote_template_id = null)
    {
        $request = $this->applicationsMetaPostRetrieveRequest($x_account_token, $application_remote_template_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\MergeATSClient\Model\MetaResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MergeATSClient\Model\MetaResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\MergeATSClient\Model\MetaResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MergeATSClient\Model\MetaResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation applicationsMetaPostRetrieveAsync
     *
     * @param  string $x_account_token Token identifying the end user. (required)
     * @param  string $application_remote_template_id The template ID associated with the nested application in the request. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function applicationsMetaPostRetrieveAsync($x_account_token, $application_remote_template_id = null)
    {
        return $this->applicationsMetaPostRetrieveAsyncWithHttpInfo($x_account_token, $application_remote_template_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation applicationsMetaPostRetrieveAsyncWithHttpInfo
     *
     * @param  string $x_account_token Token identifying the end user. (required)
     * @param  string $application_remote_template_id The template ID associated with the nested application in the request. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function applicationsMetaPostRetrieveAsyncWithHttpInfo($x_account_token, $application_remote_template_id = null)
    {
        $returnType = '\MergeATSClient\Model\MetaResponse';
        $request = $this->applicationsMetaPostRetrieveRequest($x_account_token, $application_remote_template_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'applicationsMetaPostRetrieve'
     *
     * @param  string $x_account_token Token identifying the end user. (required)
     * @param  string $application_remote_template_id The template ID associated with the nested application in the request. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function applicationsMetaPostRetrieveRequest($x_account_token, $application_remote_template_id = null)
    {
        // verify the required parameter 'x_account_token' is set
        if ($x_account_token === null || (is_array($x_account_token) && count($x_account_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_account_token when calling applicationsMetaPostRetrieve'
            );
        }

        $resourcePath = '/applications/meta/post';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($application_remote_template_id !== null) {
            if('form' === 'form' && is_array($application_remote_template_id)) {
                foreach($application_remote_template_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['application_remote_template_id'] = $application_remote_template_id;
            }
        }

        // header params
        if ($x_account_token !== null) {
            $headerParams['X-Account-Token'] = ObjectSerializer::toHeaderValue($x_account_token);
        }



        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation applicationsRetrieve
     *
     * @param  string $x_account_token Token identifying the end user. (required)
     * @param  string $id id (required)
     * @param  bool $include_remote_data Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     *
     * @throws \MergeATSClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \MergeATSClient\Model\Application
     */
    public function applicationsRetrieve($x_account_token, $id, $include_remote_data = null)
    {
        list($response) = $this->applicationsRetrieveWithHttpInfo($x_account_token, $id, $include_remote_data);
        return $response;
    }

    /**
     * Operation applicationsRetrieveWithHttpInfo
     *
     * @param  string $x_account_token Token identifying the end user. (required)
     * @param  string $id (required)
     * @param  bool $include_remote_data Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     *
     * @throws \MergeATSClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \MergeATSClient\Model\Application, HTTP status code, HTTP response headers (array of strings)
     */
    public function applicationsRetrieveWithHttpInfo($x_account_token, $id, $include_remote_data = null)
    {
        $request = $this->applicationsRetrieveRequest($x_account_token, $id, $include_remote_data);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\MergeATSClient\Model\Application' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\MergeATSClient\Model\Application', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\MergeATSClient\Model\Application';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\MergeATSClient\Model\Application',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation applicationsRetrieveAsync
     *
     * @param  string $x_account_token Token identifying the end user. (required)
     * @param  string $id (required)
     * @param  bool $include_remote_data Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function applicationsRetrieveAsync($x_account_token, $id, $include_remote_data = null)
    {
        return $this->applicationsRetrieveAsyncWithHttpInfo($x_account_token, $id, $include_remote_data)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation applicationsRetrieveAsyncWithHttpInfo
     *
     * @param  string $x_account_token Token identifying the end user. (required)
     * @param  string $id (required)
     * @param  bool $include_remote_data Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function applicationsRetrieveAsyncWithHttpInfo($x_account_token, $id, $include_remote_data = null)
    {
        $returnType = '\MergeATSClient\Model\Application';
        $request = $this->applicationsRetrieveRequest($x_account_token, $id, $include_remote_data);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'applicationsRetrieve'
     *
     * @param  string $x_account_token Token identifying the end user. (required)
     * @param  string $id (required)
     * @param  bool $include_remote_data Whether to include the original data Merge fetched from the third-party to produce these models. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function applicationsRetrieveRequest($x_account_token, $id, $include_remote_data = null)
    {
        // verify the required parameter 'x_account_token' is set
        if ($x_account_token === null || (is_array($x_account_token) && count($x_account_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_account_token when calling applicationsRetrieve'
            );
        }
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling applicationsRetrieve'
            );
        }

        $resourcePath = '/applications/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($include_remote_data !== null) {
            if('form' === 'form' && is_array($include_remote_data)) {
                foreach($include_remote_data as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['include_remote_data'] = $include_remote_data;
            }
        }

        // header params
        if ($x_account_token !== null) {
            $headerParams['X-Account-Token'] = ObjectSerializer::toHeaderValue($x_account_token);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
