<?php
/**
 * AttachmentTypeEnum
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  MergeATSClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Merge ATS API
 *
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MergeATSClient\Model;
use \MergeATSClient\ObjectSerializer;

/**
 * AttachmentTypeEnum Class Doc Comment
 *
 * @category Class
 * @package  MergeATSClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AttachmentTypeEnum
{
    /**
     * Possible values of this enum
     */
    const RESUME = 'RESUME';
    const COVER_LETTER = 'COVER_LETTER';
    const OFFER_LETTER = 'OFFER_LETTER';
    const OTHER = 'OTHER';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::RESUME,
            self::COVER_LETTER,
            self::OFFER_LETTER,
            self::OTHER,
        ];
    }
}


