<?php
/**
 * DisabilityStatusEnum
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  MergeHRISClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Merge ATS API
 *
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MergeHRISClient\Model;
use \MergeHRISClient\ObjectSerializer;

/**
 * DisabilityStatusEnum Class Doc Comment
 *
 * @category Class
 * @package  MergeHRISClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DisabilityStatusEnum
{
    /**
     * Possible values of this enum
     */
    const YES_I_HAVE_A_DISABILITY_OR_PREVIOUSLY_HAD_A_DISABILITY = 'YES_I_HAVE_A_DISABILITY_OR_PREVIOUSLY_HAD_A_DISABILITY';
    const NO_I_DONT_HAVE_A_DISABILITY = 'NO_I_DONT_HAVE_A_DISABILITY';
    const I_DONT_WISH_TO_ANSWER = 'I_DONT_WISH_TO_ANSWER';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::YES_I_HAVE_A_DISABILITY_OR_PREVIOUSLY_HAD_A_DISABILITY,
            self::NO_I_DONT_HAVE_A_DISABILITY,
            self::I_DONT_WISH_TO_ANSWER,
        ];
    }
}


