<?php
/**
 * RaceEnum
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  MergeHRISClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Merge ATS API
 *
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MergeHRISClient\Model;
use \MergeHRISClient\ObjectSerializer;

/**
 * RaceEnum Class Doc Comment
 *
 * @category Class
 * @package  MergeHRISClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RaceEnum
{
    /**
     * Possible values of this enum
     */
    const AMERICAN_INDIAN_OR_ALASKAN_NATIVE = 'AMERICAN_INDIAN_OR_ALASKAN_NATIVE';
    const ASIAN = 'ASIAN';
    const BLACK_OR_AFRICAN_AMERICAN = 'BLACK_OR_AFRICAN_AMERICAN';
    const HISPANIC_OR_LATINO = 'HISPANIC_OR_LATINO';
    const WHITE = 'WHITE';
    const NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER = 'NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER';
    const TWO_OR_MORE_RACES = 'TWO_OR_MORE_RACES';
    const DECLINE_TO_SELF_IDENTIFY = 'DECLINE_TO_SELF_IDENTIFY';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AMERICAN_INDIAN_OR_ALASKAN_NATIVE,
            self::ASIAN,
            self::BLACK_OR_AFRICAN_AMERICAN,
            self::HISPANIC_OR_LATINO,
            self::WHITE,
            self::NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER,
            self::TWO_OR_MORE_RACES,
            self::DECLINE_TO_SELF_IDENTIFY,
        ];
    }
}


